# Generated by Django 5.0.7 on 2025-06-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='', upload_to='person/'),
            preserve_default=False,
        ),
    ]
